name: takoett
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  path: ^1.9.0
  url_launcher: ^6.2.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.6.1
  flutter_config: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon/
