// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVve1I79Z_gKxzDudJmGF0KqS-pGRvNAs',
    appId: '1:543208810237:web:73b3593611fbd293bc0094',
    messagingSenderId: '543208810237',
    projectId: 'takoett',
    authDomain: 'takoett.firebaseapp.com',
    storageBucket: 'takoett.appspot.com',
    measurementId: 'G-GSN305RF2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATdVZVf0ik9CMHiAb22Bg5bkz8oAM0jOQ',
    appId: '1:543208810237:android:4f0cb10518cdc231bc0094',
    messagingSenderId: '543208810237',
    projectId: 'takoett',
    storageBucket: 'takoett.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYiqxbGrZwUpuZBbWW9iTgNe5o_DVDIf8',
    appId: '1:543208810237:ios:00b784bd56aa59cdbc0094',
    messagingSenderId: '543208810237',
    projectId: 'takoett',
    storageBucket: 'takoett.appspot.com',
    iosBundleId: 'com.example.takoett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYiqxbGrZwUpuZBbWW9iTgNe5o_DVDIf8',
    appId: '1:543208810237:ios:00b784bd56aa59cdbc0094',
    messagingSenderId: '543208810237',
    projectId: 'takoett',
    storageBucket: 'takoett.appspot.com',
    iosBundleId: 'com.example.takoett',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVve1I79Z_gKxzDudJmGF0KqS-pGRvNAs',
    appId: '1:543208810237:web:08b6b91fb8521f7cbc0094',
    messagingSenderId: '543208810237',
    projectId: 'takoett',
    authDomain: 'takoett.firebaseapp.com',
    storageBucket: 'takoett.appspot.com',
    measurementId: 'G-HMX9Y7RDJR',
  );
}
